name: file-compare-tool
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pandas
  - pyyaml
  - pip
  - tabulate
  - pip:
    - tabularcompare
    - git+https://github.com/provlab-bioinfo/search-tools