[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "file-compare-tool"
version = "0.1.0-alpha"
description = "A tool for easy comparison between tabular data."
readme = "README.md"
requires-python = ">=3.10, <4"

dependencies = [ 'pandas',
        'pyyaml',
        'build',
        'pip',
        'tabularcompare',
        'tabulate',
        'search-tools @ git+https://github.com/provlab-bioinfo/search-tools']

[project.urls]
Homepage = "https://github.com/your_username/your_custom_project"